# Generated by Django 4.2.2 on 2023-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1000, verbose_name='Никнейм')),
                ('fullname', models.CharField(max_length=1000, verbose_name='Имя')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('locale', models.CharField(default='en', max_length=4, verbose_name='Язык')),
                ('created_at', models.DateTimeField(default=False, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Все Пользователи',
                'db_table': 'users',
            },
        ),
    ]
