# Generated by Django 4.2.2 on 2023-06-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
