# Generated by Django 4.2.2 on 2023-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0005_alter_task_created_at_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
    ]
